language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - rbx-19mode
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_script:
  - mysql -e 'create database myapp_test'
  - psql -c 'create database myapp_test' -U postgres